### ISSUE TITLE
Support pam_set_data / pam_get_data

### ISSUE THREAD

**Issue by OJFord** [rcatolino/pam_sm_rust#22]
https://linux.die.net/man/3/pam_set_data
https://linux.die.net/man/3/pam_get_data

Thanks for this library! Really clear and easy to use, it actually helped me understand PAM and how to implement a 'service module' better than any docs or simple C example I could find.

Adding the ability to get/set data would be handy - used for example when the `authenticate` stage needs to store something to be used in `open_session`; or in `open_session` to instruct how to `close_session`.

Cheers.

**Comment by Natureshadow** [comment]
That woul be very helpful, alongside with the `cleanup()` callback.

**Comment by rcatolino** [comment]
I've prototyped `pam_set_data` and a trait `PamData` on the `set_get_data` branch.

So far the api looks like this : 
```
pub trait PamData: Sync {
    fn cleanup(&mut self, _pam: Pam, _flags: i32, _status: PamError) {}
}

 fn set_data<T: PamData>(&self, module_name: &str, data: Box<T>) -> PamResult<()>
```

The user has to implement the `PamData` trait on the type to set to : 
- Provide a cleanup callback
- Make sure the trait is `Sync` and can be shared in case the pam app is multithreaded.

The data has to be boxed to be allocated on the heap since the data will outlive the caller.

I'm afraid `pam_get_data` will need to be unsafe though, because I don't see how to make sure the user calls `pam_get_data` with the same type parameter as `pam_set_data`

Any ideas, suggestions ?

**Comment by OJFord** [comment]
Thanks for working on this! You've clearly put a lot more work/thought into it than I have so this is not really a _suggestion_, but is that better than having a less helpful type but that could be the same both ends? Vec/slice of u8, say?

Or perhaps anything that's both into & from that, so that rather than reconstructing in unsafe, there's a chance to handle the data not fitting the actual type?

**Comment by rcatolino** [comment]
I think you're right, storing a slice of u8 would indeed allow for a safe api. And I suspect people will mostly want to store tokens anyway.
For what it's worth I've changed the api to only allow storage of `Clone` types : 
```
    fn send_data<T: PamData + Clone + Send>(&self, module_name: &str, data: T) -> PamResult<()>;
    unsafe fn retrieve_data<T: PamData + Clone + Send>(&self, module_name: &str) -> PamResult<T>;
```
The data is now systematically cloned when retrieved, because I realized that otherwise the `retrieve_data` method would allow to create several reference to the same data without tracking by the borrow checker.

I think I can build a safe API on top of this one when `T` is `Into<&[u8]>>`  on the condition that the user doesn't use `send_data` (so I would mark `send_data` as unsafe in that case.)
